spring:
  application:
    name: Railway demo

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${{MYSQL_ROOT_PASSWORD}}
    url: jdbc:mysql://${{MYSQLUSER}}:${{MYSQL_ROOT_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{MYSQL_DATABASE}}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false