spring:
    application:
        name: Railway demo

    datasource:
        username: root
        password: 1234
        url: jdbc:mysql://localhost:3306/railway_demo?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        defer-datasource-initialization: true
#        defer-datasource-initialization: true
#        show-sql: true

    sql:
        init:
            mode: always